### ISSUE TITLE
Version 3.1.0 fails for certain template literals

### ISSUE THREAD

**Issue by stotter** [aMarCruz/rollup-plugin-cleanup#15]
Version 3.1.0 of the plugin fails if it encounters the following code.

```javascript
const v = 10;
const s = `${v}$`;

console.log(s); // prints: 10$
```

```
index.js → output.js...
[!] (cleanup plugin) Error: Unclosed ES6 Template Literal.
index.js (2:14)
1: const v = 10;
2: const s = `${v}$`;
                 ^
3:
4: console.log(s);
Error: Unclosed ES6 Template Literal.
    at error (C:\Users\stotter\temp\cleanup-test\node_modules\rollup\dist\rollup.js:3597:30)
    at Object.error (C:\Users\stotter\temp\cleanup-test\node_modules\rollup\dist\rollup.js:16497:17)
    at Object.error (C:\Users\stotter\temp\cleanup-test\node_modules\rollup\dist\rollup.js:16906:31)
    at Promise (C:\Users\stotter\temp\cleanup-test\node_modules\rollup-plugin-cleanup\dist\rollup-plugin-cleanup.js:119:20)
    at new Promise (<anonymous>)
    at Object.transform (C:\Users\stotter\temp\cleanup-test\node_modules\rollup-plugin-cleanup\dist\rollup-plugin-cleanup.js:113:16)
    at C:\Users\stotter\temp\cleanup-test\node_modules\rollup\dist\rollup.js:16609:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
```

It worked fine for version 3.0.0, so this might be related to the switch from acorn to js-cleanup.

The code above works fine in firefox, chrome and node.

I've created a small repo to reproduce the error here: https://github.com/stotter/cleanup-test

**Comment by aMarCruz** [comment]
@stotter , v3.1.1 in npm fixes this issue.
Thanks for your feedback!
